export const discipleDummyData = [
  {
    id: '1',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    community: 'Waxing Strong Commu...',
    sessionSummary: 'Daily',
    status: 'submitted',
  },
  {
    id: '2',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    community: 'Prayer Team',
    sessionSummary: 'Mon, Tue, Wed, Sat',
    status: 'due',
  },
  {
    id: '3',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    community: '',
    sessionSummary: 'Upcoming - Tuesday, 2...',
    status: 'pending',
  },
  {
    id: '4',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    community: 'Waxing Strong Commu...',
    sessionSummary: 'Mon, Tue, Wed, Sat',
    status: 'no active task',
  },
  {
    id: '5',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    community: 'Waxing Strong Commu...',
    sessionSummary: 'Mon, Tue, Wed, Sat',
    status: 'submitted',
  },
  {
    id: '6',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    community: 'Waxing Strong Commu...',
    sessionSummary: 'Mon, Tue, Wed, Sat',
    status: 'submitted',
  },
];

export const mockPastRequests = [
  {
    id: '3',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    requestDate: '24th April, 2025',
    message: '',
    status: 'accepted',
  },
  {
    id: '4',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    requestDate: '24th April, 2025',
    message: '',
    status: 'rejected',
  },
  {
    id: '5',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    requestDate: '24th April, 2025',
    message: '',
    status: 'pending',
  },

  {
    id: '7',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    requestDate: '24th April, 2025',
    message: '',
    status: 'rejected',
  },
];

export const mockPendingRequests = [
  {
    id: '1',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    requestDate: '24th April, 2025',
    message: 'Hi, I am lorem ipsum lorem ipsum lorem...',
    status: 'pending',
  },
  {
    id: '2',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    avatar: '/placeholder-avatar.jpg',
    requestDate: '24th April, 2025',
    message: 'Hi, I am lorem ipsum lorem ipsum lorem...',
    status: 'pending',
  },
];

export const mockDisciples = [
    {
        id: '1',
        firstName: 'Akwa',
        lastName: "Abasiekeme",
        avatar: '/placeholder-avatar.jpg',
        community: 'Waxing Strong Commu...',
        sessionSummary: 'Daily',
        status: 'submitted',
    },
    {
        id: '2',
        firstName: 'Akwa',
        lastName: "Abasiekeme",
        avatar: '/placeholder-avatar.jpg',
        community: 'Prayer Team',
        sessionSummary: 'Mon, Tue, Wed, Sat',
        status: 'due',
    },
    {
        id: '3',
        firstName: 'Akwa',
        lastName: "Abasiekeme",
        avatar: '/placeholder-avatar.jpg',
        community: '',
        sessionSummary: 'Upcoming - Tuesday, 2...',
        status: 'pending',
    },
    {
        id: '4',
        firstName: 'Akwa',
        lastName: "Abasiekeme",
        avatar: '/placeholder-avatar.jpg',
        community: 'Waxing Strong Commu...',
        sessionSummary: 'Mon, Tue, Wed, Sat',
        status: 'no active task',
    },
    {
        id: '5',
        firstName: 'Akwa',
        lastName: "Abasiekeme",
        avatar: '/placeholder-avatar.jpg',
        community: 'Waxing Strong Commu...',
        sessionSummary: 'Mon, Tue, Wed, Sat',
        status: 'submitted',
    },
    {
        id: '6',
        firstName: 'Akwa',
        lastName: "Abasiekeme",
        avatar: '/placeholder-avatar.jpg',
        community: 'Waxing Strong Commu...',
        sessionSummary: 'Mon, Tue, Wed, Sat',
        status: 'submitted',
    },
];

export const mockSessions = [
   {
    id: '1',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    date: '24th April, 2025',
    duration: '45mins',
  },
   {
    id: '2',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    date: '24th April, 2025',
    duration: '45mins',
  },
   {
    id: '3',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    date: '24th April, 2025',
    duration: '45mins',
  },
   {
    id: '4',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    date: '24th April, 2025',
    duration: '45mins',
  },
   {
    id: '5',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    date: '24th April, 2025',
    duration: '45mins',
  },
   {
    id: '6',
    firstName: 'Akwa',
    lastName: "Abasiekeme",
    date: '24th April, 2025',
    duration: '45mins',
  },
]
